name: 'Download project application configurations files'
description: 'Downloading project application configurations files for specified environments to the specified path on the file system'
inputs:
  login:
    description: 'Nexus login'
    required: true
  password:
    description: 'Nexus password'
    required: true
  project:
    description: 'Project system name'
    required: true
  environments:
    description: 'Environments for which configurations files should be downloaded, comma separated'
    required: true
  instances:
    description: 'Instances for which configurations files should be downloaded, comma separated, if tenant deploy process is used'
    required: false
  configs-path:
    description: 'Relative path to application configuration files location'
    required: true
runs:
  using: 'node16'
  main: './dist/index.js'