name: Self-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the action for microservice
        uses: mindbox-moscow/gha-project-config@master
        id: project-config        
        with:
          login: ${{ secrets.Nexus_Login }}
          password: ${{ secrets.Nexus_Password }}
          project: Nexus
          environments: Staging,Production
          configs-path: ./config
          instances: yandex-cloud

      - name: Run the action for project
        uses: mindbox-moscow/gha-project-config@master
        id: project-config        
        with:
          login: ${{ secrets.Nexus_Login }}
          password: ${{ secrets.Nexus_Password }}
          project: test-staging
          environments: Staging
          configs-path: ./config
